-- 계층형 쿼리
-- ORACLE
SELECT LEVEL AS LV, LPAD(' ', (LEVEL-1)*2) || EMPNO AS EMPNO, MGR, CONNECT_BY_ISLEAF AS ISLEAF
FROM EMP
START WITH MGR IS NULL
CONNECT BY EMPNO = PRIOR MGR; -- FK = PRIOR PK --> 순방향 전개

-- SQL SERVER
-- CTE  Query (Common Table Expression)
-- Anchor memeber와 Recursive memeber가 재귀적으로 Join
-- Join 결과가 빈값이면 Return
WITH T_EMP_ANCHOR AS (
-- ANCHOR Member

SELECT EMPLOYEEID, MANAGERID, 0 AS LEVEL, CONVERT(VARCHAR(1000), EMPLOYEEID) AS SORT
FROM T_EMP
WHERE MANAGERID IS NULL

UNION ALL

-- RECURSIVE Member
SELECT R.EMPLOYEEID, R.MANAGERID, A.LEVEL + 1, CONVERT(VARCHAR(1000), A.SORT + ',' + R.EMPLOYEEID) AS SORT
FROM T_EMP_ANCHOR A, T_EMP R
WHERE R.MANAGERID = A.EMPLOYEEID
)

SELECT LEVEL, REPLICATE(' ', LEVEL*2) + EMPLOYEEID AS EMPLOYEEID, MANAGERID, SORT
FROM T_EMP_ANCHOR
ORDER BY SORT -- ORDER BY를 통해 계층형으로 표현, CONVERT를 통해 데이터 형식을 통일
GO