SELECT CASE GROUPING(B.DNAME) WHEN 1 THEN 'All Departments' ELSE B.DNAME END AS DNAME,
        CASE GROUPING(A.JOB) WHEN 1 THEN 'All Jobs' ELSE A.JOB END AS JOB,
        COUNT(*) AS EMP_CNT,
        SUM(A.SAL) AS SAL_SUM
FROM EMP A, DEPT B
WHERE B.DEPTNO = A.DEPTNO
GROUP BY ROLLUP(B.DNAME, A.JOB)
ORDER BY B.DNAME, A.JOB;

-- 위와 동일한 쿼리
SELECT DECODE(GROUPING(B.DNAME), 1, 'All Departments', B.DNAME) AS DNAME,
        DECODE(GORUPING(A.JOB), 1, 'All Jobs', A.JOB) AS JOB,
        COUNT(*) AS EMP_CNT,
        SUM(A.SAL) AS SAL_SUM
FROM EMP A, DEPT B
WHERE B.DEPTNO = A.DEPTNO
GROUP BY ROLLUP(B.DNAME, A.JOB)
ORDER BY B.DNAME, A.JOB;

