-- 데이터 건수 확인
SELECT COUNT(*) FROM COVID;

-- 테이블 복제
CREATE TABLE COVID_TEMP AS SELECT * FROM COVID;

-- 전체 데이터의 Continent 값을 World로 변경
UPDATE COVID_TEMP SET CONTINENT = 'World';

--------------------------------------------------------

-- TRUNCATE & INSERT를 통한 UPDATE Tuning
CREATE TABLE COVID_TEMP_2 AS SELECT * FROM COVID;

TRUNCATE TABLE COVID_TEMP_2;

INSERT INTO COVID_TEMP_2 (ISO_CODE, CONTINENT, LOCATION, DATE_COL, TOTAL_CASES)
SELECT ISO_CODE, (SELECT 'World' FROM DUAL), LOCATION, DATE_COL, TOTAL_CASES
FROM COVID_TEMP;
